services:
  # Combined Backend + Frontend service
  - type: web
    name: reckonix-fullstack
    env: node
    plan: starter
    buildCommand: npm install && npm run build:fullstack
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/products
    autoDeploy: true
